backend:
  runtime_mode: simulation
  host: 127.0.0.1
  port: 8000
  log_level: INFO
  real_serial_default_port: ""
  real_serial_default_baud: 57600

mavlink:
  url: udpin:0.0.0.0:14551
  reconnect_sec: 1.0
  heartbeat_timeout_sec: 5.0
  default_takeoff_alt_m: 10.0

frontend:
  origin: http://127.0.0.1:5173

maps:
  provider: tencent
  default_mode: vector
  restrict_to_bounds_default: false
  default_center_lng: 118.724976
  default_center_lat: 32.206125
  default_zoom: 16
  tencent:
    vector_style: 0
    hybrid_style: 0
  bounds_w_m: 2000.0
  bounds_h_m: 2000.0
  allowed_fence_polygon_lng_lat: []
  track_max_points: 2000
  coverage_cell_size_m: 5.0
  coverage_footprint_radius_m: 6.0
