from __future__ import annotations

import argparse

from quad_rl.curriculum.presets import list_presets


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ArduPilot LOCAL_NED scan bridge with scale-aware profile selection.")
    parser.add_argument("--dry-run", type=int, default=1, help="1: no MAVLink commands, 0: send MAVLink commands")
    parser.add_argument("--sitl-recommended", type=int, default=1, choices=(0, 1))
    parser.add_argument("--sitl-recommended-source", type=str, default="latest")
    parser.add_argument("--model", type=str, default="auto", help="Model path or auto for scan profile selector")
    parser.add_argument("--task", type=str, default="scan")
    parser.add_argument("--preset", type=str, default="A2", choices=list_presets())
    parser.add_argument("--efficiency-profile", type=str, default="none", choices=("none", "best_efficiency"))
    parser.add_argument("--connection", type=str, default="udp:127.0.0.1:14550")
    parser.add_argument("--anchor-origin", type=int, default=1, choices=(0, 1))
    parser.add_argument("--scan-origin-mode", type=str, default="drone", choices=("drone", "fixed"))
    parser.add_argument("--scan-origin-ref", type=str, default="center", choices=("center", "sw", "se", "nw", "ne"))
    parser.add_argument("--scan-origin-x", type=float, default=0.0)
    parser.add_argument("--scan-origin-y", type=float, default=0.0)
    parser.add_argument("--prefer-sitl-tcp", type=int, default=1, choices=(0, 1))
    parser.add_argument("--preflight-timeout-s", type=float, default=30.0)
    parser.add_argument("--require-mode-known", type=int, default=-1)
    parser.add_argument("--ekf-mode", type=str, default="auto", choices=("auto", "strict", "wait", "ignore"))
    parser.add_argument("--ack-verbosity", type=str, default="important", choices=("all", "important"))
    parser.add_argument("--auto-guided", type=int, default=0, choices=(0, 1))
    parser.add_argument("--auto-arm", type=int, default=0, choices=(0, 1))
    parser.add_argument("--auto-takeoff-m", type=float, default=0.0)
    parser.add_argument("--steps", type=int, default=0, help="Optional hard step cap (0 disables this cap)")
    parser.add_argument("--scan-path-len-scale", type=float, default=1.0)
    parser.add_argument("--bounds-m", type=float, nargs=2, default=(40.0, 40.0), metavar=("W", "H"))
    parser.add_argument("--margin-m", type=float, default=2.0)
    parser.add_argument("--camera-hfov-deg", type=float, default=70.0)
    parser.add_argument("--camera-vfov-deg", type=float, default=50.0)
    parser.add_argument("--footprint-model", type=str, default="ellipse", choices=("ellipse", "circle_min", "circle_area"))
    parser.add_argument("--footprint-min-passes", type=int, default=1)
    parser.add_argument("--footprint-fov-scale", type=float, default=1.0)
    parser.add_argument("--footprint-count-dist-factor", type=float, default=0.3)
    parser.add_argument("--footprint-count-dist-min-m", type=float, default=0.2)
    parser.add_argument("--rate-hz", type=float, default=5.0)
    parser.add_argument("--policy-hz", type=float, default=2.0)
    parser.add_argument("--coverage-hz", type=float, default=5.0)
    parser.add_argument("--lookahead-enable", type=int, default=1, choices=(0, 1))
    parser.add_argument("--lookahead-time-s", type=float, default=0.6)
    parser.add_argument("--lookahead-cap-m", type=float, default=2.0)
    parser.add_argument("--lane-keep-enable", type=int, default=0, choices=(0, 1))
    parser.add_argument("--lane-dir-mode", type=str, default="auto", choices=("auto", "fixed"))
    parser.add_argument("--lane-kp", type=float, default=0.4)
    parser.add_argument("--lane-max-corr-m", type=float, default=1.5)
    parser.add_argument("--step-sched-enable", type=int, default=1, choices=(0, 1))
    parser.add_argument("--step-len-corner-mult", type=float, default=0.7)
    parser.add_argument("--step-len-boundary-mult", type=float, default=0.8)
    parser.add_argument("--boundary-near-m", type=float, default=3.0)
    parser.add_argument("--step-len-m", type=float, default=None)
    parser.add_argument("--accept-radius-m", type=float, default=None)
    parser.add_argument("--adaptive-tracking", type=int, default=0, choices=(0, 1))
    parser.add_argument("--adapt-interval-s", type=float, default=5.0)
    parser.add_argument("--dist-p95-high", type=float, default=2.5)
    parser.add_argument("--progress-low", type=float, default=0.2)
    parser.add_argument("--policy-hz-min", type=float, default=1.0)
    parser.add_argument("--policy-hz-max", type=float, default=3.0)
    parser.add_argument("--policy-hz-stable-dist-p95", type=float, default=1.5)
    parser.add_argument("--policy-hz-stable-progress", type=float, default=0.4)
    parser.add_argument("--step-len-min", type=float, default=2.0)
    parser.add_argument("--step-len-max", type=float, default=8.0)
    parser.add_argument("--accept-radius-min", type=float, default=0.75)
    parser.add_argument("--accept-radius-max", type=float, default=2.0)
    parser.add_argument("--max-hold-s", type=float, default=3.0)
    parser.add_argument("--alt-m", type=float, default=10.0)
    parser.add_argument("--stop-cov", type=float, default=0.95)
    parser.add_argument("--ignore-ekf", type=int, default=0)
    parser.add_argument("--clamp-stop-count", type=int, default=100)
    parser.add_argument("--oob-recovery", type=int, default=1, choices=(0, 1))
    parser.add_argument("--oob-recovery-seconds", type=float, default=3.0)
    parser.add_argument("--oob-recovery-vxy-cap", type=float, default=0.6)
    parser.add_argument("--oob-recovery-accept-boost", type=float, default=0.5)
    parser.add_argument("--oob-clamp-fast-count", type=int, default=3)
    parser.add_argument("--oob-clamp-fast-window-s", type=float, default=5.0)
    parser.add_argument("--target-refresh-mode", type=str, default="hold", choices=("hold", "always"))
    parser.add_argument("--strict-lawnmower", type=int, default=0, choices=(0, 1))
    parser.add_argument("--strict-vmin", type=float, default=0.4)
    parser.add_argument("--strict-slowdown-mult", type=float, default=3.0)
    parser.add_argument("--yaw-mode", type=str, default="none", choices=("fixed", "face-vel", "none"))
    parser.add_argument("--yaw-rate-max-dps", type=float, default=90.0)
    parser.add_argument("--return-land-on-complete", type=int, default=0, choices=(0, 1))
    parser.add_argument("--return-land-timeout-s", type=float, default=45.0)
    parser.add_argument("--return-land-radius-m", type=float, default=1.0)
    parser.add_argument("--use-vel-caps", type=int, default=1, choices=(0, 1))
    parser.add_argument("--vxy-cap", type=float, default=None)
    parser.add_argument("--vz-cap", type=float, default=0.5)
    parser.add_argument("--corner-angle-deg", type=float, default=60.0)
    parser.add_argument("--corner-slow-seconds", type=float, default=2.0)
    parser.add_argument("--corner-vxy-cap", type=float, default=0.8)
    parser.add_argument("--turn-style", type=str, default="sharp", choices=("sharp", "arc"))
    parser.add_argument("--turn-radius-m", type=float, default=2.5)
    parser.add_argument("--cfg-override", action="append", default=[], help="Override preset fields with key=value.")
    return parser.parse_args()
